const list=document.querySelector('#news-list');

function textElement(tag,className,text){const element=document.createElement(tag);if(className)element.className=className;element.textContent=text;return element}
function formatDate(value){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`))}
function createImage(post){const image=document.createElement('img');image.className='post-image';image.src=post.image;image.alt=post.alt;image.loading='lazy';image.decoding='async';return image}
function createBody(post,latest=false){const body=document.createElement('div');body.className='post-body';body.append(textElement('p','post-label',post.demo?'Demo-Beitrag':'Aktuelles'),textElement('time','post-date',formatDate(post.date)),textElement(latest?'h2':'h3','post-title',post.titel),textElement('p','post-excerpt',post.kurztext));body.querySelector('time').dateTime=post.date;const full=document.createElement('div');full.className='post-full';for(const paragraph of post.text)full.append(textElement('p','',paragraph));body.append(full);return body}
function renderLatest(post){const article=document.createElement('article');article.className='news-post latest';article.append(createImage(post),createBody(post,true));return article}
function renderOlder(post){const details=document.createElement('details');details.className='news-archive';const summary=document.createElement('summary');const date=textElement('time','archive-date',formatDate(post.date));date.dateTime=post.date;summary.append(date,textElement('span','archive-title',post.titel),textElement('span','archive-toggle','+'));const content=document.createElement('div');content.className='archive-content';content.append(createImage(post),createBody(post));details.append(summary,content);return details}

fetch('content/beitraege.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('Beiträge konnten nicht geladen werden.');return response.json()}).then(posts=>{const sorted=[...posts].sort((a,b)=>b.date.localeCompare(a.date));list.replaceChildren();if(!sorted.length){list.append(textElement('p','news-loading','Noch keine Beiträge vorhanden.'));return}list.append(renderLatest(sorted[0]));for(const post of sorted.slice(1))list.append(renderOlder(post))}).catch(()=>{list.replaceChildren(textElement('p','news-error','Die Demo-Beiträge konnten gerade nicht geladen werden.'))});
